# Generated by Django 2.2.14 on 2020-11-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='uploaded',
            field=models.DateField(auto_now_add=True),
        ),
    ]
